language: java
sudo: false
script: mvn verify jacoco:report coveralls:report -DrepoToken=dplZ1J1AfjFK3hHAj0OV8IRneKprs4Glb -Dtest=\!*ResourceTest,\!MongoPopulatorTool

#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: target/site/apidocs
#  on:
#    branch: master

notifications:
  email:
    on_sucess: never
    on_failure: always