language: java

# to try to workaround this issue: https://github.com/travis-ci/travis-ci/issues/6593
# sudo: required
# dist: precise
os: osx

script: mvn verify jacoco:report coveralls:report -DrepoToken=dplZ1J1AfjFK3hHAj0OV8IRneKprs4Glb -Dtest=\!MongoPopulatorTool

bundler_args: --retry 3

jdk:
  - oraclejdk10

#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: target/site/apidocs
#  on:
#    branch: master

notifications:
  email:
    on_sucess: never
    on_failure: always